### ISSUE TITLE
Add resource file for your language if you need SmartCommander to support it

### ISSUE THREAD

**Issue by anovik** [anovik/SmartCommander#50]
Add resource file to Assets folder for your language:

Name it like the following: Resources.ja-JP.resx

Feel free to add any language.

**Comment by Diaskhan** [comment]
We can close this issue, multilang added

**Comment by anovik** [comment]
@Diaskhan Thanks for PR but I want to leave this open in case other users will add more languages. I will add a couple of languages later myself.

**Comment by Diaskhan** [comment]
@anovik fine, the best approach would be simple instructions on wiki! 
In all cases build must be recompiled!

**Comment by Diaskhan** [comment]
@anovik 
https://crowdin.com/project/files-app

**Comment by anovik** [comment]
@Diaskhan I've created the project https://crowdin.com/project/smartcommander and added 3 new translations. Closing this. 

I am also adding the information to wiki how to add the new translation in case somebody will want to help.

**Comment by Diaskhan** [comment]
nice
